### ISSUE TITLE
Doesn't activate in Firefox (57.0.4)

### ISSUE THREAD

**Issue by Nosskirneh** [overdodactyl/Stylus-Dark#1]
Stylus doesn't seem to activate the theme, even though it _should_ match the url. I've tried other stylish editor themes as well, but since they were built for Chrome I wasn't sure what URL it filters extensions on firefox. This, however, seems to have support, but it doesn't work regardless :/

Any ideas?

**Comment by overdodactyl** [comment]
Hi there,

So I just tried it out in a new Firefox (57.0.4) profile and didn't seem to have any problems...it should immediately go into effect.

Could you possibly upload a screenshot of your main menu of Stylus?

**Comment by Nosskirneh** [comment]
<img width="1440" alt="screenshot 2018-01-23 23 27 07" src="https://user-images.githubusercontent.com/16581727/35304209-fdc6a530-0094-11e8-9410-85d7f4e82821.png">

Strange indeed.

**Comment by overdodactyl** [comment]
It appears you are using the addon [Stylish](https://addons.mozilla.org/en-US/firefox/addon/stylish/), whereas this theme was designed for [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/).

**Comment by Nosskirneh** [comment]
Oh, this is embarrassing! Well, I'm blaming the late hour.
Thanks for your patient and support!

**Comment by overdodactyl** [comment]
No worries! I'll admit they two addons look very similar :)

If your looking to mix things up, I would highly recommend Stylus.  It's open source, which is always a plus

**Comment by Nosskirneh** [comment]
Open source is something I always keep close to my heart, but I found Stylus being inferior to Stylish (easier to toggle specific themes on and off, easier preferences).

**Comment by overdodactyl** [comment]
I'm not sure if it's changed at all, but in Stylus you can toggle specific themes on/off from the menu popup as well as the settings:

![stylus](https://user-images.githubusercontent.com/33071129/35305109-0c6a3f20-0090-11e8-94db-cda462375774.png)

But, anyways, to each their own! I won't try too hard to convince ya.  Maybe I'll look into creating the same thing for Stylish

**Comment by Nosskirneh** [comment]
Had missed that part. Then I guess it's just the settings (I'm a little annoyed by not being taken directly to manage styles), but that's a very small detail so I might just switch.

**Comment by overdodactyl** [comment]
In the screenshot above, "Manage" should take you directly to manage styles and the little pencil takes you to the editing page of the corresponding style.  Is that what you mean?

**Comment by Nosskirneh** [comment]
Didn't think about that; I meant when browsing the extensions and going into 'Preferences'. That makes sense though. I'm in the middle of transferring the styles since the export/import systems didn't seem to support each other (from Stylish to Stylus).

**Comment by overdodactyl** [comment]
Oh, gotcha! That's unfortunate the export/import functions aren't compatible

**Comment by Nosskirneh** [comment]
Anyway, thanks for the support! After testing some more, Stylus is definitely way better (I made a simple dark mode for userstyles.org, and it updates live without the need for refresh!), so thanks for recommending it!

**Comment by overdodactyl** [comment]
No problem! And I'm glad you're enjoying Stylus!

**Comment by FranklinYu** [comment]
@Nosskirneh Stylus is a fork from Stylish since [it was sold to advertisement company and started to collect user browsing history](https://forum.userstyles.org/discussion/53233/announcement-to-the-community). This may not be a big deal to most users, but I think users at least need to be aware.

**Comment by Nosskirneh** [comment]
I see. Thanks for the info.
