### ISSUE TITLE
Backup buttons background isn't dark

### ISSUE THREAD

**Issue by Shiranja88** [overdodactyl/Stylus-Dark#13]
Fixed on my extension, attached the edited version.

`/* Fixing backup buttons background w/wo hover */

#backup-buttons .dropdown-content {
     background-color: #0e0e0e;
}
#backup-buttons .dropdown-content a:hover {
     background-color: #201e1e;
}`

**Comment by overdodactyl** [comment]
Thanks for the report and sorry for the delay! Fixed in #15

**Comment by StSav012** [comment]
Please commit it to userstyles.org.
