### ISSUE TITLE
Save button text looks weird with non-English Stylus

### ISSUE THREAD

**Issue by tsdko** [overdodactyl/Stylus-Dark#14]
![image](https://user-images.githubusercontent.com/2314894/50306878-f85d9980-0496-11e9-82c5-025a6d7a4ebd.png)

**Comment by overdodactyl** [comment]
Thanks for the report @tsudoko - I think the latest version should fix this, but if you could let me know that would be great!

**Comment by tsdko** [comment]
Works, thanks!
