### ISSUE TITLE
UserCSS Effects Websites

### ISSUE THREAD

**Issue by Devo7v** [overdodactyl/Stylus-Dark#16]
I'm not sure why this is, but if I install this as a UserCSS through Stylus in Firefox 65.0, it styles portions of various websites.  I tried editing the regexp to be specific to my Stylus extension, but then it just fails to style anything.  I'm not sure why this is happening.  Could this be caused by using ShadowFox?

**Comment by overdodactyl** [comment]
Which websites are you seeing this on?

**Comment by Grossdm** [comment]
@Devo7v, this userstyle uses the same regex as another userstyle for **Stylus** that I have used and I have not had problems.

On the sites with this problem, does the **Stylus** popup list **Stylus Dark** as selected?

**Comment by Devo7v** [comment]
@overdodactyl  @Grossdm, It looks like this issue went away after a couple months.  I have no idea what changed, but I can only imagine it was because I updated Firefox and Stylus a couple month ago.  You can consider this issue closed.
