### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by VChet** [overdodactyl/Stylus-Dark#9]
For now, package.json and stylus-dark.user.css have different versions.
https://github.com/overdodactyl/Stylus-Dark/blob/dee141fbf27a41eb061772fd3b4382bfb7cfbf32/stylus-dark.user.css#L3 https://github.com/overdodactyl/Stylus-Dark/blob/dee141fbf27a41eb061772fd3b4382bfb7cfbf32/package.json#L3
It may be quite monotonous to change it in both files on every update. So I suggest using [ver](https://www.npmjs.com/package/ver) and gulp tasks. With single command you could change the version in both files, commit changes and create a git tag.
[Example](https://github.com/VChet/Telegram-Vanilla-Dark/blob/master/gulpfile.js#L21)

If you're okay with this, I could make a pull request.

**Comment by overdodactyl** [comment]
I had totally forgotten about the version number in `packaga.json`..

That approach sounds great.  If you don't mind making a PR, it would be really appreciated!
